/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ing.stock.exchanger.api;

import com.ing.stock.exchanger.models.DeleteRes;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.4.0")
@Validated
@Tag(name = "stockExchange", description = "the stockExchange API")
@RequestMapping("/ingx/stock/exchanger/api")
public interface DeleteOrderApi {

    /**
     * DELETE /deleteOrder : delete pending order
     *
     * @param uniqueOrderId pending order id (optional)
     * @return Deleted (status code 200)
     */
    @Operation(
        operationId = "deleteOrderDelete",
        summary = "delete pending order",
        tags = { "stockExchange" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Deleted", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DeleteRes.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/deleteOrder",
        produces = { "application/json" }
    )
    
    ResponseEntity<DeleteRes> deleteOrderDelete(
        @Parameter(name = "uniqueOrderId", description = "pending order id", in = ParameterIn.HEADER) @RequestHeader(value = "uniqueOrderId", required = true) Long uniqueOrderId
    );

}
